set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
set mouse=a
try
source ~/.vim_runtime/my_configs.vim
catch
endtry

execute pathogen#infect()
syntax on
# set number
filetype plugin indent on
colorscheme molokai

let g:molokai_original = 1

let g:rehash256 = 1

highlight Normal ctermfg=white ctermbg=black
